media:
  input: src/media
  output: media
content:
  - name: hotels
    label: Hotel Empfehlungen
    path: src/data/hotels.json
    media:
  
    type: collection
    fields:
      - name: name
        label: Name
        type: string
      - name: image
        label: Bild-URL
        type: image
      - name: address
        label: Adresse
        type: string
      - name: price
        label: Preisspanne
        type: string
      - name: distance
        label: Entfernung
        type: string
      - name: description
        label: Beschreibung
        type: text